#!/usr/bin/env bash

# Bash script that transfers a file from our client to a server:

# Requirements:

	# Accepts 4 parameters
	# The path to the file to be transferred
	# The IP of the server we want to transfer the file to
	# The username scp connects with
	# The path to the SSH private key that scp uses
	# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
	# scp must transfer the file to the user home directory ~/
	# Strict host key checking must be disabled when using scp

# Checks if the correct number of parameter is provided

if [ $# -lt 4]; then
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
		exit 1
fi

path_to_files=$1
server_ip=$2
username=$3
ssh_private_key=$4


# Transfer the file using scp
# -i: identity file (private key)
# -o StrictHostKeyChecking=no: disable strict host key checking
scp -o StrictHostKeyChecking=no -i "$ssh_private_key" "$path_to_files" "$username"@"$server_ip":~/
