#!/usr/bin/env bash

# Install Nginx with the following configurations:
	# Listens on port 80
	# Returns a page containng "Holberton School of coding" when queried
	# at the root with a curl GET request
	# Configures /redirect_me as a "301 Moved Permanently".
	# Includes a custom 404 page containng "Ceci n'est pas une page".

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School of coding" > /etc/nginx/html/index.html

touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.html;

	location /redirect_me {
		return 301 http://cuberule.com/;
	}

	error_page 404 /404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
