#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton school" when queried
#+    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

# Create web directories with proper permissions
sudo mkdir -p /var/www/html
sudo chown -R www-data:www-data /var/www/html

# Create web content
echo "Holberton school" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx
sudo printf "%s" "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Verify configuration and restart
sudo nginx -t && sudo service nginx restart
